### ISSUE TITLE
How do I use this to create YAML snapshots?

### ISSUE THREAD

**Issue by retorquere** [ksxnodemodules/nodemonorepo#101]
I'd like to create YAML snapshots for jest, but I don't know how to use this library for it.

**Comment by KSXGitHub** [comment]
This repo is a monorepo with multiple libraries. What library are you talking about?

**Comment by retorquere** [comment]
Oh sorry - extra-jest for jest yaml snapshots

**Comment by KSXGitHub** [comment]
Use one of these functions: https://github.com/ksxnodemodules/nodemonorepo/blob/0eacc73815038641e6c2a3aabc549d489728eab1/packages/typescript/extra-jest/lib/snap.ts#L23-L27

These functions return a function, so you need to call it again.

Example:

```typescript
it('short form', safe(myObject))

it('long form', () => {
  safe(myObject)()
})
```

**Comment by retorquere** [comment]
I'm using expect(...).toMatchSpecificSnapshot(...),i know i can set something with expect.serializer but I'm not sure how.

**Comment by KSXGitHub** [comment]
> I'm using expect(...).toMatchSpecificSnapshot(...),i know i can set something with expect.serializer but I'm not sure how.

`extra-jest` wasn't made to be used in this way. You should use `js-yaml` to serialize and snapshot it yourself.

```typescript
const yaml = require('js-yaml')
expect(yaml.dump(myObject)).toMatchSnapshot()
```
